name: Android CI

on:
  schedule:
    - cron: 0 0 * * *
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y apksigner

      - uses: actions/checkout@v4
        with:
          repository: 'PojavLauncherTeam/PojavLauncher'

      - name: Patch source
        run: |
          echo 'org.gradle.jvmargs=--add-opens=java.base/java.io=ALL-UNNAMED' >>gradle.properties
          sed -i "/defaultConfig {/a ndk { abiFilters 'arm64-v8a', 'x86_64' }" app_pojavlauncher/build.gradle
          sed -i '/release {/a signingConfig signingConfigs.customDebug' app_pojavlauncher/build.gradle

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.6.4

      - name: Get JRE 8
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          path: app_pojavlauncher/src/main/assets/components/jre
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre8
          name: jre8-pojav

      - name: Get JRE17
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          path: app_pojavlauncher/src/main/assets/components/jre-new
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre17
          name: jre17-pojav

      - name: Build JRE JAR files
        run: |
          ./scripts/languagelist_updater.sh

          mkdir out
          # Build JRE JAR files (security manager, etc...)
          gradle :jre_lwjgl3glfw:build --no-daemon

      - name: Build APK
        run: |
          unset GITHUB_ACTIONS
          gradle :app_pojavlauncher:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app_pojavlauncher/build/outputs/apk/release/app_pojavlauncher-release.apk
