name: Android CI

on:
  schedule:
    - cron: 0 0 * * *
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y apksigner

      - uses: actions/checkout@v3
        with:
          repository: 'PojavLauncherTeam/PojavLauncher'

      - name: Patch source
        run: |
          echo 'org.gradle.jvmargs=--add-opens=java.base/java.io=ALL-UNNAMED' >>gradle.properties
          sed -i 's/mProfile.accessToken.equals("0")/false/g' app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/BaseLauncherActivity.java
          sed -i '/jar {/a duplicatesStrategy(DuplicatesStrategy.EXCLUDE)' jre_lwjgl3glfw/build.gradle
          sed -i '/release {/a signingConfig signingConfigs.customDebug' app_pojavlauncher/build.gradle

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current

      - name: Get gl4es latest commit hash
        id: gl4es-sha
        run: echo "::set-output name=sha::$(echo $(git ls-remote https://github.com/PojavLauncherTeam/gl4es-114-extra refs/heads/master | grep -io '^\S*'))"

      - name: Cache gl4es
        uses: actions/cache@v3
        id: gl4es-cache
        with:
          path: gl4es/libs
          key: gl4es-holy-android-shared-${{ steps.gl4es-sha.outputs.sha }}

      - name: Get gl4es
        if: steps.gl4es-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: 'PojavLauncherTeam/gl4es-114-extra'
          path: 'gl4es'

      - name: Build gl4es
        if: steps.gl4es-cache.outputs.cache-hit != 'true'
        run: |
          cd gl4es
          git config --global user.email 'github-actions@users.noreply.github.com'
          git config --global user.name 'github-actions'
          $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk
          cp -r libs/* ../app_pojavlauncher/src/main/jniLibs/

      - name: Get JRE 8
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          path: app_pojavlauncher/src/main/assets/components/jre
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre8
          name: jre8-pojav

      - name: Get JRE17
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-17.yml
          path: app_pojavlauncher/src/main/assets/components/jre-new
          workflow_conclusion: success
          repo: skbeh/android-openjdk-build-multiarch
          branch: main
          name: jre17-pojav

      - name: Build JRE JAR files
        run: |
          cp -r gl4es/libs/* app_pojavlauncher/src/main/jniLibs/
          chmod +x scripts/languagelist_updater.sh
          ./scripts/languagelist_updater.sh

          mkdir out
          # Build JRE JAR files (security manager, etc...)
          gradle :jre_lwjgl3glfw:build

      - name: Build APK
        run: |
          unset GITHUB_ACTIONS
          gradle :app_pojavlauncher:assembleRelease

      - name: Build APK without runtime
        run: |
          unset GITHUB_ACTIONS
          rm -r app_pojavlauncher/src/main/assets/components/jre
          rm -r app_pojavlauncher/src/main/assets/components/jre-new
          gradle assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app_pojavlauncher/build/outputs/apk/release/app_pojavlauncher-release.apk

      - name: Upload APK (without runtime)
        uses: actions/upload-artifact@v3
        with:
          name: app-release-noruntime
          path: app_pojavlauncher/build/outputs/apk/release/app_pojavlauncher-release.apk
